### ISSUE TITLE
Server Crash on join

### ISSUE THREAD

**Issue by fucnknown** [Fungie2134/AuthMod#2]
Well... It doesn't seem to play well with SkyFactory3

```
17:20:11] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: com/mojang/realmsclient/gui/ChatFormatting
at com.auth.mod.events.PlayerLoggedIn.PlayerLoggedIn(PlayerLoggedIn.java:20) ~[PlayerLoggedIn.class:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_881_PlayerLoggedIn_PlayerLoggedIn_PlayerLoggedInEvent.invoke(.dynamic) ~[?:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:185) ~[EventBus.class:?]
at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:565) ~[FMLCommonHandler.class:?]
at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:228) ~p.class:?]
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:260) ~[NetworkDispatcher.class:?]
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:73) ~[NetworkDispatcher.class:?]
at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:209) ~[NetworkDispatcher$1.class:?]
at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:287) ~[eo.class:?]
at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) ~d.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:732) ~[MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387) ~[ld.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) ~[MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
Caused by: java.lang.ClassNotFoundException: com.mojang.realmsclient.gui.ChatFormatting
at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_72-internal]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_72-internal]
... 16 more
Caused by: java.lang.NullPointerException
[17:20:11] [Server thread/ERROR]: This crash report has been saved to: /var/games/minecraft/servers/Cielos_Argentinos/./crash-reports/crash-2017-05-22_17.20.11-server.txt
[17:20:11] [Server thread/INFO]: Stopping server
```

Crash log attached.

[crash-2017-05-22_17.20.11-server.txt](https://github.com/Fungie2134/AuthMod/files/1020114/crash-2017-05-22_17.20.11-server.txt)

**Comment by Aang23** [comment]
Got the same error... Correcting it.

**Comment by Aang23** [comment]
Done correcting, building, testing and uploading !

**Comment by Aang23** [comment]
https://github.com/Fungie2134/AuthMod/raw/master/builds/AuthMod-1.1.jar
Working !

Curse is now working, project approved, now all build will be on Curse.

**Comment by Aang23** [comment]
I tried it on big modded server ( 238 mods exactly for testing ), and no problems detected. A release will be available soon.
